[package]
name = "optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
ir = { path = "../ir" }
model = { path = "../model" }

[dev-dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
