[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
model = { path = "../model" }
ir = { path = "../ir" }

[dev-dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }

[lints]
workspace = true
