[package]
name = "ir"
version = "0.1.0"
edition = "2024"

[dependencies]
model = { path = "../model" }

[dev-dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }

[lints]
workspace = true
